watchdog: Fix SPL builds when watchdog is enabled
Without this fix, u-boot fails to comple as it tries to load watchdog.h
during an SPL build. This breaks support for things such as the sunxi
arch.

lib/built-in.o: In function `udelay': ./u-boot/lib/time.c:167: undefined
reference to `hw_watchdog_reset'
drivers/built-in.o: In function `NS16550_putc':
./u-boot/drivers/serial/ns16550.c:217: undefined reference to
`hw_watchdog_reset'
drivers/built-in.o: In function `NS16550_getc':
./u-boot/drivers/serial/ns16550.c:228: undefined reference to
`hw_watchdog_reset'
scripts/Makefile.spl:353: recipe for target 'spl/u-boot-spl' failed
make[1]: *** [spl/u-boot-spl] Error 1
Makefile:1508: recipe for target 'spl/u-boot-spl' failed
make: *** [spl/u-boot-spl] Error 2